name: Build and Publish Box
on:
  push:
    branches: ["main"]

jobs:
  action:
    runs-on: ubuntu-latest
    env:
      PACKER_CACHE_DIR: /var/tmp/packer_cache
      VAGRANT_CLOUD_USER: 0rr0rs
      NAME: kali
      VAGRANT_CLOUD_BOX_FILE: kali-2024.3-amd64-libvirt.box
      DEBIAN_FRONTEND: noninteractive
      HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
      HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y libvirt-clients libvirt-daemon-system libvirt-daemon virtinst bridge-utils qemu qemu-system-x86
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          sudo usermod -a -G kvm,libvirt $USER
      - name: Build/Upload box
        run: |
          packer plugins install github.com/hashicorp/vagrant
          make || cat kali-2024.3-amd64-libvirt.box.log
      # - name: Upload to vagrant cloud
      #   run: |
      #     ./scripts/upload_to_vagrant_cloud.sh $VAGRANT_CLOUD_USER $NAME $VAGRANT_CLOUD_BOX_FILE
