name: Build and Publish Box
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Enable KVM group perms
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
        sudo apt-get update
        sudo apt-get install -y libvirt-clients libvirt-daemon-system libvirt-daemon virtinst bridge-utils qemu qemu-system-x86
        sudo usermod -a -G kvm,libvirt $USER
    - name: Install dependencies
      run: |
        sudo apt-get install -y qemu-kvm sysfsutils libvirt-dev
        packer plugins install github.com/hashicorp/vagrant
        make || cat kali-2024.1-amd64-libvirt.box.log
