name: Build and Publish Box
on:
  push:
    branches: ["main"]

jobs:
  action:
    runs-on: ubuntu-latest
    env:
      PACKER_CACHE_DIR: /var/tmp/packer_cache
      VAGRANT_CLOUD_USER: 0rr0rs
      NAME: kali
      VAGRANT_CLOUD_BOX_FILE: kali-2024.1-amd64-libvirt.box
      DEBIAN_FRONTEND: noninteractive
      VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: Install dependencies
        run: |
          sudo apt-get install -y libvirt-clients libvirt-daemon-system libvirt-daemon virtinst bridge-utils qemu qemu-system-x86 vagrant
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          sudo usermod -a -G kvm,libvirt $USER
      - name: Build box
        run: |
          packer plugins install github.com/hashicorp/vagrant
          make || cat kali-2024.1-amd64-libvirt.box.log
      - name: Upload to vagrant cloud
        run: |
          export BOX_VERSION=2.0.0
          if curl --silent --fail "https://vagrantcloud.com/api/v1/box/${VAGRANT_CLOUD_USER}/${NAME}" -o /dev/null; then
            vagrant cloud version create "${VAGRANT_CLOUD_USER}/${NAME}" ${BOX_VERSION}
          fi
          CHECKSUM_BOX_FILE=$(sha256sum "${VAGRANT_CLOUD_BOX_FILE}" | cut -d ' ' -f 1)
          if [[ $(curl -s "https://vagrantcloud.com/api/v1/box/${VAGRANT_CLOUD_USER}/${NAME}/version/${BOX_VERSION}/provider/libvirt" | jq -r '.checksum') != "${CHECKSUM_BOX_FILE}" ]]; then
            vagrant cloud provider create --checksum-type sha256 --checksum "${CHECKSUM_BOX_FILE}" "${VAGRANT_CLOUD_USER}/${NAME}" libvirt "${BOX_VERSION}"
            VAGRANTCLOUD_UPLOAD_PATH=$(curl -sL "https://vagrantcloud.com/api/v1/box/${VAGRANT_CLOUD_USER}/${NAME}/version/${BOX_VERSION}/provider/libvirt/upload?access_token=$VAGRANT_CLOUD_TOKEN" | jq -r '.upload_path')
            curl -X PUT --upload-file "${VAGRANT_CLOUD_BOX_FILE}" "${VAGRANTCLOUD_UPLOAD_PATH}" || true
            curl -s --output /dev/null "https://app.vagrantup.com/api/v1/box/${VAGRANT_CLOUD_USER}/${NAME}/version/${BOX_VERSION}/release" -X PUT -d "access_token=$VAGRANT_CLOUD_TOKEN"
          fi
